# Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
nums = [11,2,3,41,3] # creates a list of 5 integers
print("creates a list")
print(nums)
nums.append(10) # adds integer 10 at the end of the list
print("appends 10")
print(nums)

creates a list
[11, 2, 3, 41, 3]

In [3]:
nums.extend([12,14,16]) # extends or increases the number of elements in the list by adding integrs 12,14,16
print("add's 12,14,16")
print(nums)

add's 12,14,16
[11, 2, 3, 41, 3, 10, 12, 14, 16]

In [4]:
nums.remove(10) # finds and deletes the integer 10 from the list
print("removes 10")
print(nums)

removes 10
[11, 2, 3, 41, 3, 12, 14, 16]

In [5]:
nums.pop() # deletes the last integer or element from tje list
print("removes last element")
print(nums)

removes last element
[11, 2, 3, 41, 3, 12, 14]

In [6]:
element = nums[4] # extracts integer in the place of 4th index and stoes it in variable 'element'
print("element from 4th index")
print(element)

element from 4th index
3

In [7]:
count_of_3 = nums.count(3) # counts how many times integer 3 is there in the list
print("3 is present this meny time in list")
print(count_of_3)

3 is present this meny time in list
2

In [8]:
nums.sort() # sorts the elements in ascending order
print("sorted in ascending order")
print(nums)

sorted in ascending order
[2, 3, 3, 11, 12, 14, 41]

In [9]:
nums.reverse() # reverse's the elements of list
print("reversed elements")
print(nums)

reversed elements
[41, 14, 12, 11, 3, 3, 2]

In [10]:
nums.clear() # delets all the elements of list and keeps the list empty
print("empty list")
print(nums)

empty list
[]

#### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [11]:
# created the tuple with three names
students = ("Mohan", "Raghu", "Guruprasad")
# tryed to change the second element
students[1] = "Basavaraj"
print(students)
# give sthe error as "'tuple' object does not support item assignment"

TypeError: 'tuple' object does not support item assignment

#### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [12]:
numbers = {1,2,2,3,4,5} # created a set and inserted a same integer 2 two times
print(numbers) # but if i print only one 2 is prented

{1, 2, 3, 4, 5}

In [13]:
# set can be explained in another way
nums = [1,2,2,3,4,5] # a list with a multiple duplicate values
print(nums)
nums_in_set = set(nums) # convert it to a set

# duplicate values are removed
print(nums_in_set)

[1, 2, 2, 3, 4, 5]
{1, 2, 3, 4, 5}

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [14]:
emp_details = {
    "Name":"Basavaraj", 
    "Age":23, 
    "City":"Bangaluru"
}
print(emp_details)

emp_details["Age"] = 12  # updated the age
print(emp_details)

emp_details["email"] = "abcd@gmail.com" # added another key 'email'
print(emp_details)

{'Name': 'Basavaraj', 'Age': 23, 'City': 'Bangaluru'}
{'Name': 'Basavaraj', 'Age': 12, 'City': 'Bangaluru'}
{'Name': 'Basavaraj', 'Age': 12, 'City': 'Bangaluru', 'email': 'abcd@gmail.com'}

#### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [15]:
age =  int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote")
else:
    print("you are under age, not eligible to vote")

Enter your age:  44

You are eligible to vote

#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

marks = int(input("Enter the marks"))

if marks >= 90:
    print("Grade : A")
elif marks > 75 and marks <= 89:
    print("Grade : B")
elif marks >= 50 and marks <= 74:
    print("Grade : C")
else:
    print("Fail")

#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [16]:
number = int(input("enter a positive or negative number"))

if number <= 0:
    print("the number is 0 or in negative")
else:
    print("number is a positive number")
    if number % 2 == 0:
        print("it is also an even number")
    else:
        print("but it is not a even number")

enter a positive or negative number 3

number is a positive number
but it is not a even number

# Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [17]:
import numpy as np

scalar_array = np.array(5) # a sclar using 'np.arry(5)'
print(type(scalar_array))

<class 'numpy.ndarray'>

In [18]:
array_1D = np.array([1,2,3,4,5])
print("1D array")
print(array_1D)

1D array
[1 2 3 4 5]

In [19]:
array_2D = np.array([[1,2,3],[11,22,33]])
print("2D array")
print(array_2D)
print(f"showes the dimension of the array : {array_2D.ndim}")
print(f"prints the shape of the array :{array_2D.shape}") # shows shape of the array (2X3)

2D array
[[ 1  2  3]
 [11 22 33]]
showes the dimension of the array : 2
prints the shape of the array :(2, 3)

#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [20]:
array_using_random = np.random.randint(0, 101, size=(4, 4))
''' "(0, 101, size=(4, 4))" the first two number indicates random numbers from 0 to 100
    size tells the shape of the array'''
print(array_using_random)

[[78 27 92 55]
 [ 1 47 84 73]
 [84 79 22 55]
 [25 77 65 30]]

#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [21]:
import pandas as pd

array_3X3 =  np.random.randint(0, 1001, size=(3, 3))
print("created 2 dimensional array")
print(array_3X3)

dataframe = pd.DataFrame(array_3X3)
print("\nconverted it to DataFrame")
print(dataframe)

dataframe.columns = ['A', 'B', 'C']
print("\nadded column names to the DataFrame")
print(dataframe)

created 2 dimensional array
[[335 876 732]
 [967 918 321]
 [454 944  66]]

converted it to DataFrame
     0    1    2
0  335  876  732
1  967  918  321
2  454  944   66

added column names to the DataFrame
     A    B    C
0  335  876  732
1  967  918  321
2  454  944   66

# Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [22]:
data = [
    {"Name": "Alice", "Age": 25, "City": "New York", "Salary": 70000},
    {"Name": "Alice", "Age": 25, "City": "New York", "Salary": 70000},
    {"Name": "Bob", "Age": 30, "City": "Chicago", "Salary": 85000},
    {"Name": "Charlie", "Age": 28, "City": "San Francisco", "Salary": 95000},
    {"Name": "Diana", "Age": 35, "City": "Austin", "Salary": 105000},
    {"Name": "Ethan", "Age": 40, "City": "Seattle", "Salary": 120000},
    {"Name": "Fiona", "Age": 22, "City": "Boston", "Salary": 65000},
    {"Name": "George", "Age": 31, "City": "Denver", "Salary": 78000},
    {"Name": "Hannah", "Age": 27, "City": "Miami", "Salary": 72000},
    {"Name": "Ian", "Age": 45, "City": "Los Angeles", "Salary": 135000},
    {"Name": "Julia", "Age": 29, "City": "Atlanta", "Salary": 80000},
]

df = pd.DataFrame(data)
print(f"{df}\n")

# created the dataframe with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'.

       Name  Age           City  Salary
0     Alice   25       New York   70000
1     Alice   25       New York   70000
2       Bob   30        Chicago   85000
3   Charlie   28  San Francisco   95000
4     Diana   35         Austin  105000
5     Ethan   40        Seattle  120000
6     Fiona   22         Boston   65000
7    George   31         Denver   78000
8    Hannah   27          Miami   72000
9       Ian   45    Los Angeles  135000
10    Julia   29        Atlanta   80000

In [23]:
print("")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    11 non-null     object
 1   Age     11 non-null     int64
 2   City    11 non-null     object
 3   Salary  11 non-null     int64
dtypes: int64(2), object(2)
memory usage: 484.0+ bytes

In [24]:
# discribe gives the statistical measures of the data
df.describe()

             Age         Salary
count  11.000000      11.000000
mean   30.636364   88636.363636
std     6.888726   22743.230761
min    22.000000   65000.000000
25%    26.000000   71000.000000
50%    29.000000   80000.000000
75%    33.000000  100000.000000
max    45.000000  135000.000000

In [25]:
# prints two columns from the dataframe 
df[["Name", "City"]]

       Name           City
0     Alice       New York
1     Alice       New York
2       Bob        Chicago
3   Charlie  San Francisco
4     Diana         Austin
5     Ethan        Seattle
6     Fiona         Boston
7    George         Denver
8    Hannah          Miami
9       Ian    Los Angeles
10    Julia        Atlanta

In [26]:
# this will drop the column if it exists or do nothing if it dosent exists
df = df.drop("City", axis=1, errors="ignore")
df

       Name  Age  Salary
0     Alice   25   70000
1     Alice   25   70000
2       Bob   30   85000
3   Charlie   28   95000
4     Diana   35  105000
5     Ethan   40  120000
6     Fiona   22   65000
7    George   31   78000
8    Hannah   27   72000
9       Ian   45  135000
10    Julia   29   80000

In [27]:
# adds a nan value
df.loc[2, "Salary"] = np.nan
df

       Name  Age    Salary
0     Alice   25   70000.0
1     Alice   25   70000.0
2       Bob   30       NaN
3   Charlie   28   95000.0
4     Diana   35  105000.0
5     Ethan   40  120000.0
6     Fiona   22   65000.0
7    George   31   78000.0
8    Hannah   27   72000.0
9       Ian   45  135000.0
10    Julia   29   80000.0

In [28]:
mean_salary = df["Salary"].mean() # calculates the mean value
df["Salary"] = df["Salary"].fillna(mean_salary) # and puts it in a nan value
df

       Name  Age    Salary
0     Alice   25   70000.0
1     Alice   25   70000.0
2       Bob   30   89000.0
3   Charlie   28   95000.0
4     Diana   35  105000.0
5     Ethan   40  120000.0
6     Fiona   22   65000.0
7    George   31   78000.0
8    Hannah   27   72000.0
9       Ian   45  135000.0
10    Julia   29   80000.0

In [29]:
# delets the duplicate rows
df = df.drop_duplicates()
df

       Name  Age    Salary
0     Alice   25   70000.0
2       Bob   30   89000.0
3   Charlie   28   95000.0
4     Diana   35  105000.0
5     Ethan   40  120000.0
6     Fiona   22   65000.0
7    George   31   78000.0
8    Hannah   27   72000.0
9       Ian   45  135000.0
10    Julia   29   80000.0